# Generated by Django 4.2 on 2023-05-13 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_registration_mobile_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='Date',
            field=models.DateField(),
        ),
    ]
